apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kutt.fullname" . }}
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "kutt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kutt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kutt.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
            # Mail Settings
            - name: MAIL_HOST
              value: {{ .Values.mail.host }}
            - name: MAIL_PORT
              value: {{ .Values.mail.port | quote }}
            - name: MAIL_SECURE
              value: {{ .Values.mail.secure | quote }}
            - name: MAIL_USER
              value: {{ .Values.mail.username }}
            - name: MAIL_PASSWORD
              {{- if .Values.mail.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mail.existingSecret }}
                  key: MAIL_PASSWORD
              {{- else }}
              value: {{ .Values.mail.password }}
              {{- end }}
            # Google Settings
            - name: GOOGLE_SAFE_BROWSING_KEY
              {{- if .Values.envSecrets.google.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecrets.google.existingSecret }}
                  key: GOOGLE_SAFE_BROWSING_KEY
              {{- else }}
              value: {{ .Values.envSecrets.google.safeBrowsingKey }}
              {{- end }}
            - name: GOOGLE_ANALYTICS
              {{- if .Values.envSecrets.google.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecrets.google.existingSecret }}
                  key: GOOGLE_ANALYTICS
              {{- else }}
              value: {{ .Values.envSecrets.google.analytics }}
              {{- end }}
            - name: GOOGLE_ANALYTICS_UNIVERSAL
              {{- if .Values.envSecrets.google.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecrets.google.existingSecret }}
                  key: GOOGLE_ANALYTICS_UNIVERSAL
              {{- else }}
              value: {{ .Values.envSecrets.google.analyticsUniversal }}
              {{- end }}
            # JWT Settings
            - name: JWT_SECRET
              {{- if .Values.envSecrets.jwt.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecrets.jwt.existingSecret }}
                  key: JWT_SECRET
              {{- else }}
              value: {{ .Values.envSecrets.jwt.key }}
              {{- end }}
            # Database Settings
            - name: DB_HOST
              value: {{ include "kutt.postgresql.hostname" . | quote }}
            - name: DB_PORT
              value: {{ include "kutt.postgresql.port" . | quote }}
            - name: DB_NAME
              value: {{ include "kutt.postgresql.database" . | quote }}
            - name: DB_USER
              value: {{ include "kutt.postgresql.username" . | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kutt.postgresql.secretName" . | quote }}
                  key: {{ include "kutt.postgresql.userPasswordKey" . | quote }}
            - name: DB_SSL
              value: "false"
            # Redis Settings
            - name: REDIS_HOST
              value: {{ include "kutt.redis.hostname" . | quote }}
            - name: REDIS_PORT
              value: {{ include "kutt.redis.port" . | quote }}
            {{- if eq (include "kutt.redis.auth.enabled" .) "true" }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kutt.redis.secretName" . | quote }}
                  key: {{ include "kutt.redis.userPasswordKey" . | quote }}
            {{- end -}}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v2/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/v2/health
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
